#!/usr/bin/env bash

currentip=$(ip route get 1.1.1.1 | awk '{print$7; exit}')

cat <<EOF >> /etc/netplan/00-installer-config.yaml 
# Static IP has been set.
network:
  version: 2
  ethernets:
    enp6s18:
      dhcp4: false
      addresses:
      - $currentip/24
      routes:
        - to: default via:192.168.1.1
	  via: 192.168.1.1
      nameservers:
        addresses:




