#! /bin/env bash

read -p "Enter mount point. (i.e. /home/user/nfsstorage) " mntpoint
read -p "Enter server. (i.e. 192.168.7.122:/path/to/wherever " servip

sudo mkdir -p "$mntpoint"

sudo mount -t nfs "$servip" "$mntpoint"

sudo echo ""$servip" "$mntpoint" nfs defaults 0 0" | sudo tee -a /etc/fstab

sudo mount -a

df -h "$mntpoint"

echo "If you see the drive listed with storage info, you're good. Reboot and run df -h to check persistence"

