#!/usr/bin/env bash

if grep -q 'dhcp4: true' /etc/netplan/00-installer-config.yaml; then
  currentip=$(ip route get 1.1.1.1 | awk '{print$7; exit}')

  cat <<EOF > /etc/netplan/00-installer-config.yaml 
  ### Static IP has been set.
  network:
    version: 2
    renderer: networkd
    ethernets:
      enp6s18:
        dhcp4: false
        addresses:
          - $currentip/24
        nameservers:
          addresses:
            - 1.1.1.1
            - 1.0.0.1
        routes:
          - to: default
            via: 192.168.1.1
EOF
  netplan apply

else
  echo 'static ip already set. Be sure to make a dhcp reservation on your router for this ip.'
fi

# be sure to make dhcp reservation for this machine on your router after running this script

